### ISSUE TITLE
Definição do Produto

### ISSUE THREAD

**Issue by Pedroriq** [S204-Inatel-2023-1/StreamClass#1]
Definir produto, nome e esboço

**Comment by Pedroriq** [comment]
Foi definido o nome do produto como StreamClass, com o propósito de facilitar comunicação entre alunos e professores, auxiliando no aprendizado do aluno.

**Comment by BrandaoLuc4s** [comment]
As tecnologias definidas serão Django para realizar a aplicação Web, utilizando o banco de dados PostgreSQL. Para realização das chamadas de vídeo/áudio será o API do Zoom. Para a aplicação Mobile utilizaremos Flutter.
