### ISSUE TITLE
Design - Mobile

### ISSUE THREAD

**Issue by Pedroriq** [S204-Inatel-2023-1/StreamClass#3]
Montar design para página Mobile utilizando Figma

**Comment by BrandaoLuc4s** [comment]
Escopo da tela de login, realizado no Figma:

![Image](https://user-images.githubusercontent.com/89617278/221718515-b0ce9a90-29ca-4ba8-b984-61cae2861a42.jpeg)

Escopo da tela home, realizado no Figma:

![Image](https://user-images.githubusercontent.com/89617278/221718701-550ce37a-8309-459e-b0c9-fa196225e36b.jpeg)
